# Generated by Django 5.0.4 on 2024-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdelay',
            name='AIRLINE_AIRPORT_FLIGHTS_MONTH',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='AIRLINE_FLIGHTS_MONTH',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='AIRPORT_FLIGHTS_MONTH',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='AVG_MONTHLY_PASS_AIRLINE',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='AVG_MONTHLY_PASS_AIRPORT',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='AWND',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='CONCURRENT_FLIGHTS',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='DAY_OF_WEEK',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='DISTANCE_GROUP',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='FLT_ATTENDANTS_PER_PASS',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='GROUND_SERV_PER_PASS',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='LATITUDE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='LONGITUDE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='MONTH',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='NUMBER_OF_SEATS',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='PLANE_AGE',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='PRCP',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='SEGMENT_NUMBER',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='SNOW',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='SNWD',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flightdelay',
            name='TMAX',
            field=models.CharField(max_length=50),
        ),
    ]
