# Generated by Django 5.0.4 on 2024-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_flightdelay_airline_airport_flights_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdelay',
            name='DEP_DEL15',
            field=models.CharField(max_length=2),
        ),
    ]
